insert into tara (nume,indicativ) values ('Romania', 'RO');
insert into tara (nume,indicativ) values ('Franta', 'FR');
insert into tara (nume,indicativ) values ('Germania', 'DE');
insert into tara (nume,indicativ) values ('Italia', 'IT');
insert into tara (nume,indicativ) values ('Spania', 'ES');
insert into tara (nume,indicativ) values ('Anglia', 'UK');
insert into tara (nume,indicativ) values ('Ungaria', 'HU');
insert into tara (nume,indicativ) values ('Bulgaria', 'BG');
insert into tara (nume,indicativ) values ('Belgia', 'BE');
insert into tara (nume,indicativ) values ('Grecia', 'GR');
insert into judet (nume,indicativ, tara_fid) values ('Timis', 'TM', 1);
insert into judet (nume,indicativ, tara_fid) values ('Arad', 'AR', 1);
insert into judet (nume,indicativ, tara_fid) values ('Hunedoara', 'HD', 1);
insert into judet (nume,indicativ, tara_fid) values ('Maramures', 'MM', 1);
insert into judet (nume,indicativ, tara_fid) values ('Mehedinti', 'MH', 1);
insert into judet (nume,indicativ, tara_fid) values ('Constanta', 'CT', 1);
insert into judet (nume,indicativ, tara_fid) values ('Cluj', 'CJ', 1);
insert into judet (nume,indicativ, tara_fid) values ('Alba', 'AB', 1);
insert into judet (nume,indicativ, tara_fid) values ('Bucuresti', 'B', 1);
insert into judet (nume,indicativ, tara_fid) values ('Mures', 'MS', 1);
insert into uat (nume,judet_fid) values ('Timisoara',1);
insert into uat (nume,judet_fid) values ('Lugoj',1);
insert into uat (nume,judet_fid) values ('Arad',2);
insert into uat (nume,judet_fid) values ('Lipova',2);
insert into uat (nume,judet_fid) values ('Hunedoara',3);
insert into uat (nume,judet_fid) values ('Deva',3);
insert into uat (nume,judet_fid) values ('Simeria',3);
insert into uat (nume,judet_fid) values ('Drobeta', 5);
insert into uat (nume,judet_fid) values ('Bucuresti',9);
insert into uat (nume,judet_fid) values ('Cluj',7);
insert into sala_fitness (nume, adresa, uat_fid) values ('Gym One 1', 'str.alba iulia',8);
insert into sala_fitness (nume, adresa, uat_fid) values ('Gym One 2', 'str.emanoil gojdu',8);
insert into sala_fitness (nume, adresa, uat_fid) values ('Gym One 3', 'str.maslinului',8);
insert into sala_fitness (nume, adresa, uat_fid) values ('Gym One 4', 'str.bogdan petriceicu',8);
insert into sala_fitness (nume, adresa, uat_fid) values ('Gym One 5', 'aleea neptun',10);
insert into sala_fitness (nume, adresa, uat_fid) values ('Gym One 6', 'aleea borsec',10);
insert into sala_fitness (nume, adresa, uat_fid) values ('Gym One 7', 'calea radnei',10);
insert into sala_fitness (nume, adresa, uat_fid) values ('Gym One 8', 'aleea zorilor',12);
insert into sala_fitness (nume, adresa, uat_fid) values ('Gym One 9', 'str.eroilor',12);
insert into sala_fitness (nume, adresa, uat_fid) values ('Gym One 1', 'str.trandafirilor',12);
insert into sali_antrenament (tip_sala, numar_sali,sala_fitness_id) values ('aerobic', 2, 1);
insert into sali_antrenament (tip_sala, numar_sali,sala_fitness_id) values ('fitness', 3, 1);
insert into sali_antrenament (tip_sala, numar_sali,sala_fitness_id) values ('yoga', 1, 1);
insert into sali_antrenament (tip_sala, numar_sali,sala_fitness_id) values ('sauna', 1, 2);
insert into sali_antrenament (tip_sala, numar_sali,sala_fitness_id) values ('pilates', 2, 3);
insert into sali_antrenament (tip_sala, numar_sali,sala_fitness_id) values ('bazin', 2, 1);
insert into sali_antrenament (tip_sala, numar_sali,sala_fitness_id) values ('aerobic', 1, 5);
insert into sali_antrenament (tip_sala, numar_sali,sala_fitness_id) values ('fitness', 3, 6);
insert into sali_antrenament (tip_sala, numar_sali,sala_fitness_id) values ('fitness', 5, 8);
insert into sali_antrenament (tip_sala, numar_sali,sala_fitness_id) values ('sauna', 2, 10);
insert into tip_abonament (tip_abonament) values ('Good Morning');
insert into tip_abonament (tip_abonament) values ('KIDS - Clasa MAMI’Eu');
insert into tip_abonament (tip_abonament) values ('Pilates class');
insert into tip_abonament (tip_abonament) values ('Full Time Fitness');
insert into tip_abonament (tip_abonament) values ('Full Fitness + Aerobic');
insert into tip_abonament (tip_abonament) values ('Full Fitness + Cycling');
insert into tip_abonament (tip_abonament) values ('Yoga class');
insert into tip_abonament (tip_abonament) values ('Bodybuilding'); 
insert into tip_abonament (tip_abonament) values ('Sauna'); 
insert into tip_abonament (tip_abonament) values ('Masaj'); 
insert into abonament (durata_luni,tarif,sala_fitness_id,id_tip_abonament) values (1,100, 1, 1); 
insert into abonament (durata_luni,tarif,sala_fitness_id,id_tip_abonament) values (2,200, 2, 2); 
insert into abonament (durata_luni,tarif,sala_fitness_id,id_tip_abonament) values (3,300, 1, 3); 
insert into abonament (durata_luni,tarif, sala_fitness_id,id_tip_abonament) values (12,1000,1, 4); 
insert into abonament (durata_luni,tarif, sala_fitness_id,id_tip_abonament) values (5,500, 5, 7); 
insert into abonament (durata_luni,tarif, sala_fitness_id,id_tip_abonament) values (4,400, 3, 5); 
insert into abonament (durata_luni,tarif, sala_fitness_id,id_tip_abonament) values (3,300, 2, 10); 
insert into abonament (durata_luni, tarif,sala_fitness_id,id_tip_abonament) values (6,600, 4, 6); 
insert into abonament (durata_luni, tarif,sala_fitness_id,id_tip_abonament) values (5,500, 10, 2); 
insert into abonament (durata_luni, tarif,sala_fitness_id,id_tip_abonament) values (2,200, 9, 8); 
insert into membri (cod_membru,data_inscriere) values ('as300', '2022-01-10');
insert into membri (cod_membru,data_inscriere) values ('am400', '2020-04-05');
insert into membri (cod_membru,data_inscriere) values ('an500', '2023-02-18');
insert into membri (cod_membru,data_inscriere) values ('nb600', '2022-02-24');
insert into membri (cod_membru,data_inscriere) values ('ar500', '2024-08-10');
insert into membri (cod_membru,data_inscriere) values ('fn800', '2025-01-10');
insert into membri (cod_membru,data_inscriere) values ('dm900', '2024-02-11');
insert into membri (cod_membru,data_inscriere) values ('as700', '2022-11-21');
insert into membri (cod_membru,data_inscriere) values ('lm400', '2023-02-12');
insert into membri (cod_membru,data_inscriere) values ('rd500', '2021-03-17');
insert into persoane (nume, numar_telefon, membri_id) values ('Maria', '0712345678',1);
insert into persoane (nume, numar_telefon, membri_id) values ('Andrei', '0712345679',10);
insert into persoane (nume, numar_telefon, membri_id) values ('Mihai', '0712345677',11);
insert into persoane (nume, numar_telefon, membri_id) values ('Ioana', '0712345676',12);
insert into persoane (nume, numar_telefon, membri_id) values ('Andreea', '0712345675',13);
insert into persoane (nume, numar_telefon, membri_id) values ('Valentin', '0712345674',14);
insert into persoane (nume, numar_telefon, membri_id) values ('Marius', '0712345673',16);
insert into persoane (nume, numar_telefon, membri_id) values ('Mihai', '0712345672',15);
insert into persoane (nume, numar_telefon, membri_id) values ('Roxana', '0712345670',17);
insert into persoane (nume, numar_telefon, membri_id) values ('Mihaela', '0712345660',18);
insert into antrenori (nume, sala_fitness_id) values ('Alex', 1);
insert into antrenori (nume, sala_fitness_id) values ('Alexandra', 2);
insert into antrenori (nume, sala_fitness_id) values ('Ana', 3);
insert into antrenori (nume, sala_fitness_id) values ('Cristina', 4);
insert into antrenori (nume, sala_fitness_id) values ('Irina', 5);
insert into antrenori (nume, sala_fitness_id) values ('Fabian', 6);
insert into antrenori (nume, sala_fitness_id) values ('Ion', 7);
insert into antrenori (nume, sala_fitness_id) values ('Florin', 8);
insert into antrenori (nume, sala_fitness_id) values ('Cristian', 9);
insert into antrenori (nume, sala_fitness_id) values ('Daniela', 10);
insert into specializare (nume_specializare) values ('yoga');
insert into specializare (nume_specializare) values ('bodybuilding');
insert into specializare (nume_specializare) values ('inot');
insert into specializare (nume_specializare) values ('fitness');
insert into specializare (nume_specializare) values ('pilates');
insert into specializare (nume_specializare) values ('Personal Trainer & Nutriție');
insert into specializare (nume_specializare) values ('aerobic');
insert into specializare (nume_specializare) values ('stretching');
insert into specializare (nume_specializare) values ('dans sportiv');
insert into specializare (nume_specializare) values ('zumba');
insert into antrenori_specializare (specializare_id,antrenori_id) values (1,1);
insert into antrenori_specializare (specializare_id,antrenori_id) values (2,1);
insert into antrenori_specializare (specializare_id,antrenori_id) values (3,3);
insert into antrenori_specializare (specializare_id,antrenori_id) values (4,5);
insert into antrenori_specializare (specializare_id,antrenori_id) values (6,8);
insert into antrenori_specializare (specializare_id,antrenori_id) values (2,4);
insert into antrenori_specializare (specializare_id,antrenori_id) values (5,10);
insert into antrenori_specializare (specializare_id,antrenori_id) values (1,5);
insert into antrenori_specializare (specializare_id,antrenori_id) values (3,9);
insert into antrenori_specializare (specializare_id,antrenori_id) values (2,8);